### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np

In [17]:
vector = np.random.rand(10)

matrix = np.array([[11, 14, 17],
                    [20, 23, 26],
                    [29, 32, 35]])

In [18]:
vector, vector.shape, matrix, matrix.shape

(array([0.18747902, 0.2877498 , 0.33581288, 0.21449914, 0.54550178,
        0.78987695, 0.63489346, 0.11450267, 0.55979392, 0.56082764]),
 (10,),
 array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [19]:
vector_plus_10 = np.round(vector + 10, 2)
vector_plus_10

array([10.19, 10.29, 10.34, 10.21, 10.55, 10.79, 10.63, 10.11, 10.56,
       10.56])

In [20]:
matrix_mult2 = matrix * 2
matrix_mult2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [21]:
vector_squared = vector ** 2
vector_squared

array([0.03514838, 0.08279994, 0.11277029, 0.04600988, 0.29757219,
       0.62390559, 0.40308971, 0.01311086, 0.31336924, 0.31452764])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [22]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [23]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

Оскільки розмірність вектора `С` 2х1, а розмірність матриці `result_matrix` 2х2, то в результаті отримаємо вектор розмірністю 2х1.










In [24]:
result_matrix_mult_C = np.dot(result_matrix, C)
result_matrix_mult_C

array([[0.5202],
       [0.2846]])

Оскільки розмірність матриці `D` 2х2, а розмірність матриці `result_matrix` 2х2, то в результаті отримаємо матрицю розмірністю 2х2.  

In [25]:
result_matrix_mult_D = np.dot(result_matrix, D)
result_matrix_mult_D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [26]:
result_matrix_T = result_matrix.T
result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [29]:
vector_T = vector.T
vector_T, vector_T.shape

(array([0.18747902, 0.2877498 , 0.33581288, 0.21449914, 0.54550178,
        0.78987695, 0.63489346, 0.11450267, 0.55979392, 0.56082764]),
 (10,))

Розмірність транспонованого вектора не змінилась.




In [31]:
column_vector = np.expand_dims(vector, axis=1)
column_vector

array([[0.18747902],
       [0.2877498 ],
       [0.33581288],
       [0.21449914],
       [0.54550178],
       [0.78987695],
       [0.63489346],
       [0.11450267],
       [0.55979392],
       [0.56082764]])

In [32]:
column_vector.shape

(10, 1)

Розмірність `column_vector` змінилась впорівнянні з `vector`. Тепер це вектор-стовпець.

In [33]:
column_vector_T = column_vector.T
column_vector_T, column_vector_T.shape

(array([[0.18747902, 0.2877498 , 0.33581288, 0.21449914, 0.54550178,
         0.78987695, 0.63489346, 0.11450267, 0.55979392, 0.56082764]]),
 (1, 10))

Тепер `column_vector_T` є двовимірним масивом.